name: Get Unity License File

# Этот workflow запускается ОДИН РАЗ для получения лицензии Unity.
# После получения файла — он больше не нужен.

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request Unity license activation file
    runs-on: ubuntu-latest
    steps:

      - name: Request manual activation file
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.45f1

      - name: Upload activation file (.alf)
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v2022.3.45f1.alf
          path: Unity_v2022.3.45f1.alf
          retention-days: 1
